language: python
python:
  - "2.7"


# command to install dependencies
install:
  - sudo apt-get install -qq uuid-dev
  - pip install tox


# command to run tests
script:
  - tox -e $TOXENV

env:
  - TOXENV=django16-haystack231-xapian1219
  - TOXENV=django16-haystackmaster-xapian1219

